#ifndef GFC2SPATIALSTRUCTUREELEMENTBINARYSERIALIZER_H
#define GFC2SPATIALSTRUCTUREELEMENTBINARYSERIALIZER_H

#include "Gfc2ObjectBinarySerializer.h"

class Gfc2SpatialStructureElementBinarySerializer: public Gfc2ObjectBinarySerializer
{
OBJECTBUF_DEC_OBJECT(Gfc2SpatialStructureElementBinarySerializer,glodon::objectbuf::EntitySerializer)
};
#endif
